"use client";

import SqlCodeBlock from "@/components/ui/sql/SqlCodeBlock";
import SqlTableBlock from "@/components/ui/sql/SqlTableBlock";
import SqlResultBlock from "@/components/ui/sql/SqlResultBlock";
import { useAccordionSection } from "@/hooks/useAccordionSection";
import { sqlToTableDiagram } from "@/data/sqlSyntax";
import { MdExpandMore, MdCode, MdAccountTree, MdLibraryBooks, MdCheckCircle, MdGridOn, MdInfo, MdTableChart, MdKey, MdLink } from "react-icons/md";
import { FaCode } from "react-icons/fa6";
import { usePathname } from "next/navigation";
import { SECTION_DESC_COLORS } from "@/config/colors";

export default function AccordionSection({
  title,
  content,
  sqlCode,
  explanation,
  sqlDiagram,
  sqlSchema,
  sqlResult,
  sqlTable,
  externalComponent,
  description,
  className = "",
}) {
  const { isOpen, toggleOpen } = useAccordionSection();
  const pathname = usePathname();
  
  // Determine current belt and get colors
  const currentBelt = pathname?.split("/")[1];
  const colors = SECTION_DESC_COLORS[currentBelt] || SECTION_DESC_COLORS.white;

  // Auto-generate table diagram from SQL code if it contains CREATE TABLE
  const autoGeneratedTables = sqlCode && sqlCode.includes('CREATE TABLE') 
    ? sqlToTableDiagram(sqlCode) 
    : null;

  // Check if this is DDL (Data Definition Language) content
  const isDDL = sqlCode && (
    sqlCode.includes('CREATE TABLE') || 
    sqlCode.includes('ALTER TABLE') || 
    sqlCode.includes('DROP TABLE')
  );

  return (
    <div
      className={`mb-6 border border-gray-200 rounded-xl shadow-sm ${className}`}
    >
      {/* Accordion header */}
      <button
        onClick={toggleOpen}
        className={`w-full text-left p-6 flex items-center justify-between bg-white hover:bg-gray-50 transition-colors duration-200 focus:outline-none relative cursor-pointer ${
          isOpen ? "rounded-t-xl" : "rounded-xl"
        }`}
      >
        <div className="flex items-center space-x-3">
          <div className={`p-2 rounded-lg ${colors.bg} transition-opacity duration-200`}>
            <FaCode className={`w-4 h-4 ${colors.text}`} />
          </div>
          <h3 className="text-lg font-semibold text-gray-900">{title}</h3>
        </div>
        <MdExpandMore
          className={`w-6 h-6 text-gray-500 transition-transform duration-200 ${
            isOpen ? "rotate-180" : ""
          }`}
        />
      </button>

      {/* Accordion content */}
      {isOpen && (
        <div className="p-6 bg-white space-y-6 rounded-b-xl border-t border-gray-200">
          {/* Description - only show if content exists */}
          {content && (
            <div className={`${colors.bg} ${colors.border} border-l-4 p-6 rounded-r-lg`}>
              <p className={`${colors.text} leading-relaxed`}>{content}</p>
            </div>
          )}

          {/* External Component */}
          {externalComponent && (
            <div>
              <div>
                {externalComponent}
              </div>
            </div>
          )}

          {/* SQL Code */}
          {sqlCode && (
            <div>
              <h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center">
                <MdCode className="w-4 h-4 mr-2 text-blue-600" />
                SQL Code
              </h4>
              <SqlCodeBlock>{sqlCode}</SqlCodeBlock>
            </div>
          )}

          {/* Diagram */}
          {sqlDiagram && (
            <div>
              <h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center">
                <MdAccountTree className="w-4 h-4 mr-2 text-slate-600" />
                Diagram
              </h4>
              <SqlTableBlock title="Database Diagram">
                {sqlDiagram}
              </SqlTableBlock>
            </div>
          )}

          {/* Auto-generated Table Diagram from CREATE TABLE statements - SANS container mac */}
          {autoGeneratedTables && autoGeneratedTables.length > 0 && (
            <div>
              <h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center">
                <MdAccountTree className="w-4 h-4 mr-2 text-emerald-600" />
                Structure des Tables
              </h4>
              <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
                {autoGeneratedTables.map((table, tableIndex) => (
                  <div
                    key={tableIndex}
                    className="bg-white border border-gray-300 rounded-lg overflow-hidden shadow-sm"
                  >
                    {/* Table Header */}
                    <div className="bg-gray-50 px-4 py-3 border-b border-gray-200">
                      <h3 className="text-gray-800 font-semibold text-sm font-mono flex items-center justify-center">
                        <MdTableChart className="w-4 h-4 mr-2" />
                        {table.name}
                      </h3>
                    </div>

                    {/* Columns */}
                    <div className="divide-y divide-gray-200">
                      {table.columns?.map((column, colIndex) => (
                        <div
                          key={colIndex}
                          className={`px-4 py-2 text-sm font-mono flex items-center justify-between hover:bg-gray-50 transition-colors ${
                            column.isPrimary ? "bg-blue-50" : ""
                          } ${column.isForeign ? "bg-purple-50" : ""}`}
                        >
                          <div className="flex items-center space-x-2">
                            {/* Icône de clé */}
                            {column.isPrimary && (
                              <MdKey className="w-3 h-3 text-blue-600" />
                            )}
                            {column.isForeign && (
                              <MdLink className="w-3 h-3 text-purple-600" />
                            )}
                            
                            {/* Nom de la colonne */}
                            <span className="text-gray-800 font-medium">
                              {column.name}
                            </span>
                          </div>

                          {/* Type de données */}
                          <div className="text-right">
                            <span className="text-blue-600 text-xs font-medium">
                              {column.type}
                            </span>
                            {column.constraints && (
                              <div className="text-violet-600 text-xs mt-1">
                                {column.constraints}
                              </div>
                            )}
                          </div>
                        </div>
                      ))}
                    </div>

                    {/* Relationships */}
                    {table.relationships && table.relationships.length > 0 && (
                      <div className="bg-gray-50 px-4 py-2 border-t border-gray-200">
                        <div className="text-xs text-gray-600 mb-1 font-medium">Relations:</div>
                        {table.relationships.map((rel, relIndex) => (
                          <div
                            key={relIndex}
                            className="text-xs text-purple-700 flex items-center font-mono"
                          >
                            <MdLink className="w-3 h-3 mr-1" />
                            {rel.column} → {rel.referencedTable}.{rel.referencedColumn}
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Schema - SUPPRIMÉ selon demande utilisateur */}
          {/* sqlSchema && (
            <div>
              <h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center">
                <MdLibraryBooks className="w-4 h-4 mr-2 text-purple-600" />
                Table Schema
              </h4>
              <SqlTableBlock tables={sqlSchema} title="Table Schema" />
            </div>
          ) */}

          {/* Results - SEULEMENT pour non-DDL */}
          {sqlResult && !isDDL && (
            <div>
              <h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center">
                <MdCheckCircle className="w-4 h-4 mr-2 text-green-600" />
                Query Result
              </h4>
              <SqlResultBlock data={sqlResult} title="Query Result" />
            </div>
          )}

          {/* Data Table */}
          {sqlTable && (
            <div>
              <h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center">
                <MdGridOn className="w-4 h-4 mr-2 text-indigo-600" />
                Table Data
              </h4>
              <SqlTableBlock data={sqlTable} title="Table Data" />
            </div>
          )}

          {/* Explanation - SUPPRIMÉ selon demande utilisateur */}
          {/* (explanation || description) && (
            <div className="bg-blue-50 border-l-4 border-blue-400 p-4 rounded-r-lg">
              <div className="flex items-start">
                <MdInfo className="w-5 h-5 text-blue-600 mr-2 mt-0.5 flex-shrink-0" />
                <div>
                  <h4 className="text-sm font-semibold text-blue-900 mb-1">
                    {explanation ? "Explanation" : "Description"}
                  </h4>
                  <p className="text-blue-800 text-sm leading-relaxed">
                    {explanation || description}
                  </p>
                </div>
              </div>
            </div>
          ) */}
        </div>
      )}
    </div>
  );
}
