"use client";

import LazyWrapper from "@/components/ui/LazyWrapper";
import SqlCodeBlock from "@/components/ui/sql/SqlCodeBlock";
import SqlResultBlock from "@/components/ui/sql/SqlResultBlock";
import SqlTableBlock from "@/components/ui/sql/SqlTableBlock";
import { BELT_COLORS } from "@/config/belts-config";
import { sqlToTableDiagram } from "@/config/sql-syntax";
import { useNavigation } from "@/hooks/useNavigation";
import { useState } from "react";
import { FaCode } from "react-icons/fa6";
import {
	MdAccountTree,
	MdCheckCircle,
	MdCode,
	MdExpandMore,
	MdGridOn,
	MdKey,
	MdLink,
	MdTableChart,
} from "react-icons/md";

export default function Accordion({
	title,
	content,
	sqlCode,
	sqlQueries,
	explanation,
	sqlDiagram,
	sqlSchema,
	sqlResult,
	sqlTable,
	externalComponent,
	description,
	className = "",
}) {
	const [isOpen, setIsOpen] = useState(false);
	const { current } = useNavigation();

	// Determine current belt and get colors
	const currentBelt = current?.href?.split("/")[1];
	const colors = BELT_COLORS[currentBelt] || BELT_COLORS.white;

	// Auto-generate table diagram from SQL code if it contains CREATE TABLE
	const autoGeneratedTables =
		sqlCode && sqlCode.includes("CREATE TABLE")
			? sqlToTableDiagram(sqlCode)
			: null;

	// Check if this is DDL (Data Definition Language) content
	const isDDL =
		sqlCode &&
		(sqlCode.includes("CREATE TABLE") ||
			sqlCode.includes("ALTER TABLE") ||
			sqlCode.includes("DROP TABLE"));

	const toggle = () => setIsOpen(!isOpen);

	return (
		<div
			className={`border-accordion ${
				isOpen ? "open" : ""
			} bg-white rounded-lg shadow-sm ${
				colors.text || "text-gray-700"
			} ${className}`}
		>
			{/* Accordion header */}
			<button
				onClick={toggle}
				className={`w-full text-left p-6 bg-white transition-opacity duration-200 focus:outline-none relative ${
					isOpen ? "rounded-t-lg" : "rounded-lg"
				}`}
			>
				<div className="flex flex-col space-y-2 flex-1">
					<div className="flex items-center space-x-3">
						<FaCode className={`w-5 h-5 ${colors.text || "text-gray-700"}`} />
						<h3 className="text-lg font-semibold">{title}</h3>
					</div>
				</div>
				<MdExpandMore
					className={`w-6 h-6 text-gray-500 transition-transform duration-200 absolute top-6 right-6 ${
						isOpen ? "rotate-180" : ""
					}`}
				/>
			</button>

			{/* Accordion content */}
			{isOpen && (
				<div
					className="p-6 bg-white flex flex-col space-y-6 rounded-b-lg border-t"
					style={{ borderTopColor: "currentColor" }}
				>
					{/* Description - only show if content exists */}
					{content && (
						<div
							className={`bg-gray-50 border border-gray-200 rounded-lg p-4 ${
								colors.text || "text-gray-700"
							}`}
						>
							<p className="leading-relaxed">{content}</p>
						</div>
					)}

					{/* External Component */}
					{externalComponent && (
						<LazyWrapper>
							<div>{externalComponent}</div>
						</LazyWrapper>
					)}

					{/* SQL Queries - Nouvelle structure avec requêtes individuelles */}
					{sqlQueries && sqlQueries.length > 0 && (
						<div className="space-y-6">
							<h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center">
								<MdCode className="w-4 h-4 mr-2 text-blue-600" />
								Requêtes SQL et Résultats
							</h4>
							{sqlQueries.map((query, index) => (
								<div
									key={index}
									className="space-y-4 border border-gray-200 rounded-lg p-4"
								>
									<h5 className="text-sm font-medium text-gray-800 border-l-4 border-blue-500 pl-3">
										{query.title}
									</h5>
									<SqlCodeBlock>{query.sqlCode}</SqlCodeBlock>
									<div className="mt-3">
										<h6 className="text-xs font-semibold text-gray-700 mb-2 flex items-center">
											<MdCheckCircle className="w-3 h-3 mr-1 text-green-600" />
											Résultat
										</h6>
										{Array.isArray(query.sqlResult) ? (
											<SqlResultBlock
												data={query.sqlResult}
												title={`Résultat - ${query.title}`}
											/>
										) : query.sqlResult?.message ? (
											<SqlResultBlock
												message={query.sqlResult.message}
												title={`Résultat - ${query.title}`}
												type="message"
											/>
										) : (
											<SqlResultBlock
												data={query.sqlResult}
												title={`Résultat - ${query.title}`}
											/>
										)}
									</div>
								</div>
							))}
						</div>
					)}

					{/* SQL Code - structure originale maintenue pour compatibilité */}
					{sqlCode && (
						<div>
							<h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center">
								<MdCode className="w-4 h-4 mr-2 text-blue-600" />
								SQL Code
							</h4>
							<SqlCodeBlock>{sqlCode}</SqlCodeBlock>
						</div>
					)}

					{/* Diagram */}
					{sqlDiagram && (
						<div>
							<h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center">
								<MdAccountTree className="w-4 h-4 mr-2 text-slate-600" />
								Diagram
							</h4>
							<SqlTableBlock title="Database Diagram">
								{sqlDiagram}
							</SqlTableBlock>
						</div>
					)}

					{/* Auto-generated Table Diagram from CREATE TABLE statements */}
					{autoGeneratedTables && autoGeneratedTables.length > 0 && (
						<div>
							<h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center">
								<MdAccountTree className="w-4 h-4 mr-2 text-emerald-600" />
								Structure des Tables
							</h4>
							<div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
								{autoGeneratedTables.map((table, tableIndex) => (
									<div
										key={tableIndex}
										className="bg-white border border-gray-300 rounded-lg overflow-hidden shadow-sm"
									>
										<div className="bg-gray-50 px-4 py-3 border-b border-gray-200">
											<h3 className="text-gray-800 font-semibold text-sm font-mono flex items-center justify-center">
												<MdTableChart className="w-4 h-4 mr-2" />
												{table.name}
											</h3>
										</div>
										<div className="divide-y divide-gray-200">
											{table.columns?.map((column, colIndex) => (
												<div
													key={colIndex}
													className={`px-4 py-2 text-sm font-mono flex items-center justify-between hover:bg-gray-50 transition-colors ${
														column.isPrimary ? "bg-blue-50" : ""
													} ${column.isForeign ? "bg-purple-50" : ""}`}
												>
													<div className="flex items-center space-x-2">
														{column.isPrimary && (
															<MdKey className="w-3 h-3 text-blue-600" />
														)}
														{column.isForeign && (
															<MdLink className="w-3 h-3 text-purple-600" />
														)}
														<span className="text-gray-800 font-medium">
															{column.name}
														</span>
													</div>
													<div className="text-right">
														<span className="text-blue-600 text-xs font-medium">
															{column.type}
														</span>
														{column.constraints && (
															<div className="text-violet-600 text-xs mt-1">
																{column.constraints}
															</div>
														)}
													</div>
												</div>
											))}
										</div>
										{table.relationships && table.relationships.length > 0 && (
											<div className="bg-gray-50 px-4 py-2 border-t border-gray-200">
												<div className="text-xs text-gray-600 mb-1 font-medium">
													Relations:
												</div>
												{table.relationships.map((rel, relIndex) => (
													<div
														key={relIndex}
														className="text-xs text-purple-700 flex items-center font-mono"
													>
														<MdLink className="w-3 h-3 mr-1" />
														{rel.column} → {rel.referencedTable}.
														{rel.referencedColumn}
													</div>
												))}
											</div>
										)}
									</div>
								))}
							</div>
						</div>
					)}

					{/* Results - SEULEMENT pour non-DDL */}
					{sqlResult && !isDDL && (
						<div>
							<h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center">
								<MdCheckCircle className="w-4 h-4 mr-2 text-green-600" />
								Résultat de la Requête
							</h4>
							{Array.isArray(sqlResult) ? (
								<SqlResultBlock
									data={sqlResult}
									title="Résultat de la Requête"
								/>
							) : sqlResult.message ? (
								<SqlResultBlock
									message={sqlResult.message}
									title="Résultat de la Requête"
									type="message"
								/>
							) : (
								<SqlResultBlock
									data={sqlResult}
									title="Résultat de la Requête"
								/>
							)}
						</div>
					)}

					{/* Data Table */}
					{sqlTable && (
						<div>
							<h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center">
								<MdGridOn className="w-4 h-4 mr-2 text-indigo-600" />
								Table Data
							</h4>
							<SqlTableBlock data={sqlTable} title="Table Data" />
						</div>
					)}
				</div>
			)}
		</div>
	);
}
