"use client";

import SQLCodeBlock from "@/components/ui/sql/SQLCodeBlock";
import SQLResultBlock from "@/components/ui/sql/SQLResultBlock";
import SQLTableDiagram from "@/components/ui/sql/SQLTableDiagram";
import { BELT_COLORS } from "@/config/belts-config";
import { sqlToTableDiagram } from "@/config/sql-syntax";
import { Suspense, useState } from "react";
import { FaCode } from "react-icons/fa6";
import {
	MdAccountTree,
	MdCheckCircle,
	MdCode,
	MdExpandMore,
} from "react-icons/md";

// Helper to render SQL result
const renderSqlResult = (sqlResult) => {
	if (Array.isArray(sqlResult)) {
		return <SQLResultBlock data={sqlResult} />;
	}
	if (sqlResult?.message) {
		return <SQLResultBlock message={sqlResult.message} type="message" />;
	}
	return <SQLResultBlock data={sqlResult} />;
};

export default function Accordion({
	title,
	content,
	examples, // Nouvelle structure unifiée
	sqlCode, // Rétrocompatibilité
	sqlQueries, // Rétrocompatibilité
	sqlResult, // Rétrocompatibilité
	externalComponent,
	colors = BELT_COLORS.white,
	className = "",
}) {
	const [isOpen, setIsOpen] = useState(false);
	const accordionId = `accordion-${title.replace(/\s+/g, "-").toLowerCase()}`;

	// Debug: log examples
	if (title.includes("INNER JOIN") || title.includes("clés primaires")) {
		console.log(`[${title}] examples:`, examples);
		console.log(`[${title}] sqlQueries:`, sqlQueries);
		console.log(`[${title}] sqlCode:`, sqlCode);
	}

	// Auto-generate table diagram from SQL code if it contains CREATE TABLE
	const autoGeneratedTables =
		sqlCode && sqlCode.includes("CREATE TABLE")
			? sqlToTableDiagram(sqlCode)
			: null;

	// Check if this is DDL (Data Definition Language) content
	const isDDL =
		sqlCode &&
		(sqlCode.includes("CREATE TABLE") ||
			sqlCode.includes("ALTER TABLE") ||
			sqlCode.includes("DROP TABLE"));

	const toggle = () => setIsOpen(!isOpen);

	return (
		<div
			className={`border-accordion ${
				isOpen ? "open" : ""
			} bg-white rounded-lg shadow-sm ${
				colors.text || "text-gray-700"
			} ${className}`}
		>
			{/* Accordion header */}
			<button
				id={`${accordionId}-header`}
				onClick={toggle}
				aria-expanded={isOpen}
				aria-controls={`${accordionId}-content`}
				className={`w-full text-left p-6 bg-white transition-opacity duration-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-blue-500 relative cursor-pointer ${
					isOpen ? "rounded-t-lg" : "rounded-lg"
				}`}
			>
				<div className="flex flex-col space-y-2 flex-1">
					<div className="flex items-center space-x-3">
						<FaCode
							className={`w-5 h-5 ${colors.text || "text-gray-700"}`}
							aria-hidden="true"
						/>
						<h3 className="text-lg font-semibold">{title}</h3>
					</div>
				</div>
				<MdExpandMore
					className={`w-6 h-6 text-gray-500 transition-transform duration-200 absolute top-6 right-6 ${
						isOpen ? "rotate-180" : ""
					}`}
					aria-hidden="true"
				/>
			</button>

			{/* Accordion content - using grid for smooth animation */}
			<div
				id={`${accordionId}-content`}
				role="region"
				aria-labelledby={`${accordionId}-header`}
				aria-hidden={!isOpen}
				className={`grid transition-[grid-template-rows] duration-300 ease-in-out ${
					isOpen ? "grid-rows-[1fr]" : "grid-rows-[0fr]"
				}`}
			>
				<div className="overflow-hidden">
					<div
						className="p-6 bg-white flex flex-col space-y-6 rounded-b-lg border-t cursor-default"
						style={{ borderTopColor: "currentColor" }}
					>
						{/* Description - only show if content exists */}
						{content && (
							<div
								className={`bg-gray-50 border border-gray-200 rounded-lg p-4 ${
									colors.text || "text-gray-700"
								}`}
							>
								<p
									className="leading-relaxed whitespace-pre-line content-html"
									dangerouslySetInnerHTML={{ __html: content }}
								/>
							</div>
						)}

					{/* External Component */}
					{externalComponent && (
						<Suspense
							fallback={
								<div className="flex items-center justify-center p-8">
									<div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
									<span className="ml-3 text-gray-600">Chargement...</span>
								</div>
							}
						>
							<div>{externalComponent}</div>
						</Suspense>
					)}

					{/* New unified examples structure */}
					{examples && examples.length > 0 && (
						<div className="space-y-6">
							{examples.map((example, index) => {
								const exampleType = example.type || "query"; // default to "query"
								
								return (
									<div
										key={index}
										className="space-y-4 border border-gray-200 rounded-lg p-4"
									>
										{example.title && (
											<h5 className="text-sm font-medium text-gray-800 border-l-4 border-blue-500 pl-3 mb-3">
												{example.title}
											</h5>
										)}

										{exampleType === "schema" ? (
											// Schema: CREATE TABLE with auto-generated diagram
											<>
												<SQLCodeBlock>{example.code}</SQLCodeBlock>
												{example.code && example.code.includes("CREATE TABLE") && (
													<div className="mt-4">
														<h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center">
															<MdAccountTree className="w-4 h-4 mr-2 text-emerald-600" />
															Structure des tables
														</h4>
														<div className="flex flex-wrap gap-6 items-start">
															{sqlToTableDiagram(example.code).map((table, tableIndex) => (
																<SQLTableDiagram key={tableIndex} table={table} />
															))}
														</div>
													</div>
												)}
											</>
										) : (
											// Query: Regular SQL with optional result
											<>
												<SQLCodeBlock>{example.code}</SQLCodeBlock>
												{example.result !== undefined && (
													<div className="mt-3">{renderSqlResult(example.result)}</div>
												)}
											</>
										)}
									</div>
								);
							})}
						</div>
					)}

					{/* Legacy: SQL Queries (backwards compatibility) */}
					{!examples && sqlQueries && sqlQueries.length > 0 && (
							<div className="space-y-6">

								{sqlQueries.map((query, index) => (
									<div
										key={index}
										className="space-y-4 border border-gray-200 rounded-lg p-4"
									>
									{query.title && (
										<h5 className="text-sm font-medium text-gray-800 border-l-4 border-blue-500 pl-3 mb-3">
											{query.title}
										</h5>
									)}
									<SQLCodeBlock>{query.sqlCode}</SQLCodeBlock>
									{query.sqlResult !== undefined && (
										<div className="mt-3">{renderSqlResult(query.sqlResult)}</div>
									)}
									</div>
								))}
						</div>
				)}

				{/* Legacy: SQL Code (backwards compatibility) */}
				{!examples && sqlCode && <SQLCodeBlock>{sqlCode}</SQLCodeBlock>}

				{/* Legacy: Auto-generated Table Diagram from CREATE TABLE statements */}
					{!examples && autoGeneratedTables && autoGeneratedTables.length > 0 && (
						<div>
							<h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center">
								<MdAccountTree className="w-4 h-4 mr-2 text-emerald-600" />
								Structure des tables
							</h4>
							<div className="flex flex-wrap gap-6 items-start">
								{autoGeneratedTables.map((table, tableIndex) => (
									<SQLTableDiagram key={tableIndex} table={table} />
								))}
							</div>
					</div>
					)}

				{/* Legacy: Results (backwards compatibility) */}
				{!examples && sqlResult && !isDDL && (
					<div>
						<h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center">
							<MdCheckCircle className="w-4 h-4 mr-2 text-green-600" />
							Résultat de la Requête
						</h4>
						{renderSqlResult(sqlResult)}
					</div>
				)}
				</div>
			</div>
		</div>
	</div>
);
}