"use client";

import SqlCodeBlock from "@/components/ui/sql/SqlCodeBlock";
import SqlResultBlock from "@/components/ui/sql/SqlResultBlock";
import SqlTableBlock from "@/components/ui/sql/SqlTableBlock";
import { BELT_COLORS } from "@/config/belts-config";
import { sqlToTableDiagram } from "@/config/sql-syntax";
import { Suspense, useState } from "react";
import { FaCode } from "react-icons/fa6";
import {
	MdAccountTree,
	MdCheckCircle,
	MdCode,
	MdExpandMore,
	MdKey,
	MdLink,
	MdTableChart,
} from "react-icons/md";

export default function Accordion({
	title,
	content,
	sqlCode,
	sqlQueries,
	sqlDiagram,
	sqlResult,
	externalComponent,
	colors = BELT_COLORS.white,
	className = "",
}) {
	const [isOpen, setIsOpen] = useState(false);
	const accordionId = `accordion-${title.replace(/\s+/g, "-").toLowerCase()}`;

	// Auto-generate table diagram from SQL code if it contains CREATE TABLE
	const autoGeneratedTables =
		sqlCode && sqlCode.includes("CREATE TABLE")
			? sqlToTableDiagram(sqlCode)
			: null;

	// Check if this is DDL (Data Definition Language) content
	const isDDL =
		sqlCode &&
		(sqlCode.includes("CREATE TABLE") ||
			sqlCode.includes("ALTER TABLE") ||
			sqlCode.includes("DROP TABLE"));

	const toggle = () => setIsOpen(!isOpen);

	return (
		<div
			className={`border-accordion ${
				isOpen ? "open" : ""
			} bg-white rounded-lg shadow-sm ${
				colors.text || "text-gray-700"
			} ${className}`}
		>
			{/* Accordion header */}
			<button
				id={`${accordionId}-header`}
				onClick={toggle}
				aria-expanded={isOpen}
				aria-controls={`${accordionId}-content`}
				className={`w-full text-left p-6 bg-white transition-opacity duration-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-blue-500 relative cursor-pointer ${
					isOpen ? "rounded-t-lg" : "rounded-lg"
				}`}
			>
				<div className="flex flex-col space-y-2 flex-1">
					<div className="flex items-center space-x-3">
						<FaCode
							className={`w-5 h-5 ${colors.text || "text-gray-700"}`}
							aria-hidden="true"
						/>
						<h3 className="text-lg font-semibold">{title}</h3>
					</div>
				</div>
				<MdExpandMore
					className={`w-6 h-6 text-gray-500 transition-transform duration-200 absolute top-6 right-6 ${
						isOpen ? "rotate-180" : ""
					}`}
					aria-hidden="true"
				/>
			</button>

			{/* Accordion content - using grid for smooth animation */}
			<div
				id={`${accordionId}-content`}
				role="region"
				aria-labelledby={`${accordionId}-header`}
				aria-hidden={!isOpen}
				className={`grid transition-[grid-template-rows] duration-300 ease-in-out ${
					isOpen ? "grid-rows-[1fr]" : "grid-rows-[0fr]"
				}`}
			>
				<div className="overflow-hidden">
					<div
						className="p-6 bg-white flex flex-col space-y-6 rounded-b-lg border-t cursor-default"
						style={{ borderTopColor: "currentColor" }}
					>
						{/* Description - only show if content exists */}
						{content && (
							<div
								className={`bg-gray-50 border border-gray-200 rounded-lg p-4 ${
									colors.text || "text-gray-700"
								}`}
							>
								<p
									className="leading-relaxed whitespace-pre-line content-html"
									dangerouslySetInnerHTML={{ __html: content }}
								/>
							</div>
						)}

						{/* External Component */}
						{externalComponent && (
							<Suspense
								fallback={
									<div className="flex items-center justify-center p-8">
										<div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
										<span className="ml-3 text-gray-600">Chargement...</span>
									</div>
								}
							>
								<div>{externalComponent}</div>
							</Suspense>
						)}

						{/* SQL Queries */}
						{sqlQueries && sqlQueries.length > 0 && (
							<div className="space-y-6">
								<h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center">
									<MdCode className="w-4 h-4 mr-2 text-blue-600" />
									SQL code et résultats
								</h4>
								{sqlQueries.map((query, index) => (
									<div
										key={index}
										className="space-y-4 border border-gray-200 rounded-lg p-4"
									>
										{query.title && (
											<h5 className="text-sm font-medium text-gray-800 border-l-4 border-blue-500 pl-3 mb-3">
												{query.title}
											</h5>
										)}
										<SqlCodeBlock>{query.sqlCode}</SqlCodeBlock>
										{query.sqlResult !== undefined && (
											<div className="mt-3">
												{Array.isArray(query.sqlResult) ? (
													<SqlResultBlock data={query.sqlResult} />
												) : query.sqlResult?.message ? (
													<SqlResultBlock
														message={query.sqlResult.message}
														type="message"
													/>
												) : (
													<SqlResultBlock data={query.sqlResult} />
												)}
											</div>
										)}
									</div>
								))}
							</div>
						)}

						{/* SQL Code */}
						{sqlCode && (
							<div>
								<h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center">
									<MdCode className="w-4 h-4 mr-2 text-blue-600" />
									SQL Code
								</h4>
								<SqlCodeBlock>{sqlCode}</SqlCodeBlock>
							</div>
						)}

						{/* Diagram */}
						{sqlDiagram && (
							<div>
								<h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center">
									<MdAccountTree className="w-4 h-4 mr-2 text-slate-600" />
									Diagram
								</h4>
								<SqlTableBlock title="Database Diagram">
									{sqlDiagram}
								</SqlTableBlock>
							</div>
						)}

						{/* Auto-generated Table Diagram from CREATE TABLE statements */}
						{autoGeneratedTables && autoGeneratedTables.length > 0 && (
							<div>
								<h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center">
									<MdAccountTree className="w-4 h-4 mr-2 text-emerald-600" />
									Structure des tables
								</h4>
								<div className="flex flex-wrap gap-6 items-start">
									{autoGeneratedTables.map((table, tableIndex) => (
										<div
											key={tableIndex}
											className="bg-white border border-gray-300 rounded-lg shadow-sm w-full md:w-[calc(50%-12px)] lg:w-[calc(33.333%-16px)]"
										>
											<div className="bg-gray-50 px-4 py-3 border-b border-gray-200 rounded-t-lg">
												<h3 className="text-gray-800 font-semibold text-sm font-mono flex items-center justify-center">
													<MdTableChart className="w-4 h-4 mr-2" />
													{table.name}
												</h3>
											</div>
											<div>
												{table.columns?.map((column, colIndex) => (
													<div
														key={colIndex}
														className={`px-4 py-2 text-sm font-mono border-b border-gray-200 last:border-b-0 hover:bg-gray-50 transition-colors ${
															column.isPrimary ? "bg-blue-50" : ""
														} ${column.isForeign ? "bg-purple-50" : ""}`}
													>
														<div className="flex items-start gap-3">
															<div className="flex-shrink-0 w-5 flex items-center justify-center pt-0.5">
																{column.isPrimary && (
																	<MdKey className="w-3 h-3 text-blue-600" />
																)}
																{column.isForeign && (
																	<MdLink className="w-3 h-3 text-purple-600 opacity-80" />
																)}
															</div>
															<div className="flex-shrink-0 text-gray-800 font-medium">
																{column.name}
															</div>
														</div>
														<div className="mt-1 ml-8 text-right">
															<div className="text-blue-600 text-xs font-medium break-words text-left">
																{column.type}
															</div>
															{column.constraints && (
																<div className="text-violet-600 text-xs mt-0.5 break-words text-left">
																	{column.constraints}
																</div>
															)}
														</div>
													</div>
												))}
											</div>
											{table.relationships &&
												table.relationships.length > 0 && (
													<div className="bg-gray-50 px-4 py-2 border-t border-gray-200">
														<div className="text-xs text-gray-600 mb-1 font-medium">
															Relations:
														</div>
														{table.relationships.map((rel, relIndex) => (
															<div
																key={relIndex}
																className="text-xs text-purple-700 flex items-center font-mono"
															>
																<MdLink className="w-3 h-3 mr-1 flex-shrink-0" />
																<span className="break-all">
																	{rel.column} → {rel.referencedTable}.
																	{rel.referencedColumn}
																</span>
															</div>
														))}
													</div>
												)}
										</div>
									))}
								</div>
							</div>
						)}

						{/* Results */}
						{sqlResult && !isDDL && (
							<div>
								<h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center">
									<MdCheckCircle className="w-4 h-4 mr-2 text-green-600" />
									Résultat de la Requête
								</h4>
								{Array.isArray(sqlResult) ? (
									<SqlResultBlock
										data={sqlResult}
										title="Résultat de la Requête"
									/>
								) : sqlResult.message ? (
									<SqlResultBlock
										message={sqlResult.message}
										title="Résultat de la Requête"
										type="message"
									/>
								) : (
									<SqlResultBlock
										data={sqlResult}
										title="Résultat de la Requête"
									/>
								)}
							</div>
						)}
					</div>
				</div>
			</div>
		</div>
	);
}
